---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: janus-role
rules:
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    resourceNames: ["nonroot"]
    verbs: ["use"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: janus-rolebinding
subjects:
  - kind: ServiceAccount
    name: janus-custom-sa
roleRef:
  kind: Role
  name: janus-role
  apiGroup: rbac.authorization.k8s.io