apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: janusgraph-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Janusgraph is the Schema for the janusgraphs API
      displayName: Janusgraph
      kind: Janusgraph
      name: janusgraphs.graph.ibm.com
      version: v1alpha1
  description: Janusgraph Operator for OpenShift
  displayName: Janusgraph Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - JanusGraph
  - Operator
  - Openshift
  links:
  - name: Janusgraph Operator
    url: https://janusgraph-operator.domain
  maturity: alpha
  provider:
    name: IBM
  version: 0.0.0
