kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: cassandra  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cassandra
    spec:
    #   volumes:
    #     - name: cassandra-data
    #       persistentVolumeClaim:
    #         claimName: cassandra-data
      containers:
        - resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 768Mi
          terminationMessagePath: /dev/termination-log
          name: cassandra
          command:
            - /bin/sh
          env:
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: CASSANDRA_SEEDS
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: CASSANDRA_CLUSTER_NAME
              value: K8Demo
            - name: CASSANDRA_DC
              value: DC1-K8Demo
            - name: CASSANDRA_RACK
              value: Rack1-K8Demo
            - name: CASSANDRA_START_RPC
              value: 'true'
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: CASSANDRA_BROADCAST_RPC_ADDRESS
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: CASSANDRA_BROADCAST_ADDRESS
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: CASSANDRA_LISTEN_ADDRESS
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: CASSANDRA_RPC_ADDRESS
              value: 0.0.0.0
          ports:
            - name: intra-node
              containerPort: 7000
              protocol: TCP
            - name: tls-intra-node
              containerPort: 7001
              protocol: TCP
            - name: jmx
              containerPort: 7199
              protocol: TCP
            - name: cql
              containerPort: 9042
              protocol: TCP
            - name: thrift
              containerPort: 9160
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: cassandra-data
              mountPath: /cassandra_data
          terminationMessagePolicy: File
          image: 'sanjeevghimire/cassandra:1.0'
          args:
            - '-c'
            - cassandra -Rf
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}      
  serviceName: ''
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10
  volumeClaimTemplates:
  - metadata:
      name: cassandra-data      
      labels:
         app: cassandra
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ibmc-vpc-block-10iops-tier"
      resources:
        requests:
          storage: 1Gi